"""Init

Revision ID: 4c3adf4ea248
Revises: 
Create Date: 2026-04-02 11:16:24.761903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3adf4ea248'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('age_months', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_sessions_id'), 'patient_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_patient_sessions_patient_name'), 'patient_sessions', ['patient_name'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_sessions_patient_name'), table_name='patient_sessions')
    op.drop_index(op.f('ix_patient_sessions_id'), table_name='patient_sessions')
    op.drop_table('patient_sessions')
    # ### end Alembic commands ###
